import React from "react";

interface PrintViewProps {
  rows: any[];
  productionName?: string;
}

export default function CastingPrintView({ rows, productionName = "Cast List" }: PrintViewProps) {
  
  // Sort by Role Name for the print view (optional, but looks nicer)
  const sortedRows = [...rows].sort((a, b) => {
      const roleA = a.role?.[0]?.value || "";
      const roleB = b.role?.[0]?.value || "";
      return roleA.localeCompare(roleB);
  });

  return (
    <div className="hidden print:block fixed inset-0 z-[9999] bg-white text-black p-12 overflow-y-auto">
      
      {/* HEADER */}
      <div className="flex justify-between items-end border-b-4 border-black pb-4 mb-8">
        <div>
            <h1 className="text-4xl font-black uppercase tracking-widest">{productionName}</h1>
            <p className="text-sm text-gray-500 mt-2 font-medium uppercase tracking-wide">
                Official Cast List
            </p>
        </div>
        <div className="text-right">
            <p className="font-bold text-xl">{rows.filter(r => r.person && r.person.length > 0).length} Roles Cast</p>
            <p className="text-sm text-gray-500">{new Date().toLocaleDateString()}</p>
        </div>
      </div>

      {/* TABLE */}
      <table className="w-full text-left text-sm border-collapse">
        <thead>
          <tr className="border-b-2 border-black">
            <th className="py-2 px-4 font-black uppercase text-lg w-1/2">Role</th>
            <th className="py-2 px-4 font-black uppercase text-lg w-1/2 text-right">Cast Member</th>
          </tr>
        </thead>
        <tbody>
          {sortedRows.map((row, index) => {
            const isAssigned = row.person && row.person.length > 0;
            
            // Handle multiple actors (Double Casting) nicely
            const actorNames = isAssigned 
                ? row.person.map((p: any) => p.value).join(" / ") 
                : "OPEN";

            return (
              <tr key={row.id} className={`border-b border-gray-200 break-inside-avoid ${index % 2 === 0 ? 'bg-gray-50' : 'bg-white'}`}>
                <td className="py-4 px-4 font-bold text-base align-middle">
                    {row.role?.[0]?.value || "Unknown Role"}
                </td>
                <td className={`py-4 px-4 font-medium text-base align-middle text-right ${!isAssigned ? 'text-gray-300 italic' : ''}`}>
                    {actorNames}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      {/* FOOTER */}
      <div className="mt-12 pt-6 border-t border-gray-300 text-center text-xs text-gray-400 font-mono">
        Generated by Open Backstage • {new Date().toLocaleDateString()}
      </div>

    </div>
  );
}